function [BW_out,properties] = filterRegionsCircles(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 21-Oct-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[1000 + eps(1000), Inf]);%filtrar para deixar o que for >1000

% Get properties.
properties = regionprops(BW_out, {'Area', 'ConvexArea', 'FilledArea', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});